# Generated by Django 6.0 on 2026-01-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(default='GET', max_length=20)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('response_status', models.IntegerField()),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='analytics_r_timesta_4da77d_idx'), models.Index(fields=['ip_address'], name='analytics_r_ip_addr_8f959c_idx'), models.Index(fields=['endpoint'], name='analytics_r_endpoin_f480f5_idx')],
            },
        ),
    ]
